/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandsRouteImport } from './routes/stands'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EvenementielRouteImport } from './routes/evenementiel'
import { Route as CreationsRouteImport } from './routes/creations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StandsIndexRouteImport } from './routes/stands.index'
import { Route as CommunicationIndexRouteImport } from './routes/communication.index'
import { Route as StandsProductRouteImport } from './routes/stands.$product'
import { Route as CommunicationSignaletiqueRouteImport } from './routes/communication.signaletique'
import { Route as CommunicationImpressionRouteImport } from './routes/communication.impression'
import { Route as CommunicationCategoryRouteImport } from './routes/communication.$category'
import { Route as CommunicationSignaletiqueIndexRouteImport } from './routes/communication.signaletique.index'
import { Route as CommunicationImpressionIndexRouteImport } from './routes/communication.impression.index'
import { Route as CommunicationSignaletiqueProductRouteImport } from './routes/communication.signaletique.$product'
import { Route as CommunicationImpressionProductRouteImport } from './routes/communication.impression.$product'

const StandsRoute = StandsRouteImport.update({
  id: '/stands',
  path: '/stands',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementielRoute = EvenementielRouteImport.update({
  id: '/evenementiel',
  path: '/evenementiel',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsRoute = CreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandsIndexRoute = StandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StandsRoute,
} as any)
const CommunicationIndexRoute = CommunicationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunicationRoute,
} as any)
const StandsProductRoute = StandsProductRouteImport.update({
  id: '/$product',
  path: '/$product',
  getParentRoute: () => StandsRoute,
} as any)
const CommunicationSignaletiqueRoute =
  CommunicationSignaletiqueRouteImport.update({
    id: '/signaletique',
    path: '/signaletique',
    getParentRoute: () => CommunicationRoute,
  } as any)
const CommunicationImpressionRoute = CommunicationImpressionRouteImport.update({
  id: '/impression',
  path: '/impression',
  getParentRoute: () => CommunicationRoute,
} as any)
const CommunicationCategoryRoute = CommunicationCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => CommunicationRoute,
} as any)
const CommunicationSignaletiqueIndexRoute =
  CommunicationSignaletiqueIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CommunicationSignaletiqueRoute,
  } as any)
const CommunicationImpressionIndexRoute =
  CommunicationImpressionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CommunicationImpressionRoute,
  } as any)
const CommunicationSignaletiqueProductRoute =
  CommunicationSignaletiqueProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => CommunicationSignaletiqueRoute,
  } as any)
const CommunicationImpressionProductRoute =
  CommunicationImpressionProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => CommunicationImpressionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/communication': typeof CommunicationRouteWithChildren
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRoute
  '/evenementiel': typeof EvenementielRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stands': typeof StandsRouteWithChildren
  '/communication/$category': typeof CommunicationCategoryRoute
  '/communication/impression': typeof CommunicationImpressionRouteWithChildren
  '/communication/signaletique': typeof CommunicationSignaletiqueRouteWithChildren
  '/stands/$product': typeof StandsProductRoute
  '/communication/': typeof CommunicationIndexRoute
  '/stands/': typeof StandsIndexRoute
  '/communication/impression/$product': typeof CommunicationImpressionProductRoute
  '/communication/signaletique/$product': typeof CommunicationSignaletiqueProductRoute
  '/communication/impression/': typeof CommunicationImpressionIndexRoute
  '/communication/signaletique/': typeof CommunicationSignaletiqueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRoute
  '/evenementiel': typeof EvenementielRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/communication/$category': typeof CommunicationCategoryRoute
  '/stands/$product': typeof StandsProductRoute
  '/communication': typeof CommunicationIndexRoute
  '/stands': typeof StandsIndexRoute
  '/communication/impression/$product': typeof CommunicationImpressionProductRoute
  '/communication/signaletique/$product': typeof CommunicationSignaletiqueProductRoute
  '/communication/impression': typeof CommunicationImpressionIndexRoute
  '/communication/signaletique': typeof CommunicationSignaletiqueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/communication': typeof CommunicationRouteWithChildren
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRoute
  '/evenementiel': typeof EvenementielRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stands': typeof StandsRouteWithChildren
  '/communication/$category': typeof CommunicationCategoryRoute
  '/communication/impression': typeof CommunicationImpressionRouteWithChildren
  '/communication/signaletique': typeof CommunicationSignaletiqueRouteWithChildren
  '/stands/$product': typeof StandsProductRoute
  '/communication/': typeof CommunicationIndexRoute
  '/stands/': typeof StandsIndexRoute
  '/communication/impression/$product': typeof CommunicationImpressionProductRoute
  '/communication/signaletique/$product': typeof CommunicationSignaletiqueProductRoute
  '/communication/impression/': typeof CommunicationImpressionIndexRoute
  '/communication/signaletique/': typeof CommunicationSignaletiqueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/communication'
    | '/contact'
    | '/creations'
    | '/evenementiel'
    | '/sitemap.xml'
    | '/stands'
    | '/communication/$category'
    | '/communication/impression'
    | '/communication/signaletique'
    | '/stands/$product'
    | '/communication/'
    | '/stands/'
    | '/communication/impression/$product'
    | '/communication/signaletique/$product'
    | '/communication/impression/'
    | '/communication/signaletique/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/creations'
    | '/evenementiel'
    | '/sitemap.xml'
    | '/communication/$category'
    | '/stands/$product'
    | '/communication'
    | '/stands'
    | '/communication/impression/$product'
    | '/communication/signaletique/$product'
    | '/communication/impression'
    | '/communication/signaletique'
  id:
    | '__root__'
    | '/'
    | '/communication'
    | '/contact'
    | '/creations'
    | '/evenementiel'
    | '/sitemap.xml'
    | '/stands'
    | '/communication/$category'
    | '/communication/impression'
    | '/communication/signaletique'
    | '/stands/$product'
    | '/communication/'
    | '/stands/'
    | '/communication/impression/$product'
    | '/communication/signaletique/$product'
    | '/communication/impression/'
    | '/communication/signaletique/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunicationRoute: typeof CommunicationRouteWithChildren
  ContactRoute: typeof ContactRoute
  CreationsRoute: typeof CreationsRoute
  EvenementielRoute: typeof EvenementielRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StandsRoute: typeof StandsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stands': {
      id: '/stands'
      path: '/stands'
      fullPath: '/stands'
      preLoaderRoute: typeof StandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementiel': {
      id: '/evenementiel'
      path: '/evenementiel'
      fullPath: '/evenementiel'
      preLoaderRoute: typeof EvenementielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations': {
      id: '/creations'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof CreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stands/': {
      id: '/stands/'
      path: '/'
      fullPath: '/stands/'
      preLoaderRoute: typeof StandsIndexRouteImport
      parentRoute: typeof StandsRoute
    }
    '/communication/': {
      id: '/communication/'
      path: '/'
      fullPath: '/communication/'
      preLoaderRoute: typeof CommunicationIndexRouteImport
      parentRoute: typeof CommunicationRoute
    }
    '/stands/$product': {
      id: '/stands/$product'
      path: '/$product'
      fullPath: '/stands/$product'
      preLoaderRoute: typeof StandsProductRouteImport
      parentRoute: typeof StandsRoute
    }
    '/communication/signaletique': {
      id: '/communication/signaletique'
      path: '/signaletique'
      fullPath: '/communication/signaletique'
      preLoaderRoute: typeof CommunicationSignaletiqueRouteImport
      parentRoute: typeof CommunicationRoute
    }
    '/communication/impression': {
      id: '/communication/impression'
      path: '/impression'
      fullPath: '/communication/impression'
      preLoaderRoute: typeof CommunicationImpressionRouteImport
      parentRoute: typeof CommunicationRoute
    }
    '/communication/$category': {
      id: '/communication/$category'
      path: '/$category'
      fullPath: '/communication/$category'
      preLoaderRoute: typeof CommunicationCategoryRouteImport
      parentRoute: typeof CommunicationRoute
    }
    '/communication/signaletique/': {
      id: '/communication/signaletique/'
      path: '/'
      fullPath: '/communication/signaletique/'
      preLoaderRoute: typeof CommunicationSignaletiqueIndexRouteImport
      parentRoute: typeof CommunicationSignaletiqueRoute
    }
    '/communication/impression/': {
      id: '/communication/impression/'
      path: '/'
      fullPath: '/communication/impression/'
      preLoaderRoute: typeof CommunicationImpressionIndexRouteImport
      parentRoute: typeof CommunicationImpressionRoute
    }
    '/communication/signaletique/$product': {
      id: '/communication/signaletique/$product'
      path: '/$product'
      fullPath: '/communication/signaletique/$product'
      preLoaderRoute: typeof CommunicationSignaletiqueProductRouteImport
      parentRoute: typeof CommunicationSignaletiqueRoute
    }
    '/communication/impression/$product': {
      id: '/communication/impression/$product'
      path: '/$product'
      fullPath: '/communication/impression/$product'
      preLoaderRoute: typeof CommunicationImpressionProductRouteImport
      parentRoute: typeof CommunicationImpressionRoute
    }
  }
}

interface CommunicationImpressionRouteChildren {
  CommunicationImpressionProductRoute: typeof CommunicationImpressionProductRoute
  CommunicationImpressionIndexRoute: typeof CommunicationImpressionIndexRoute
}

const CommunicationImpressionRouteChildren: CommunicationImpressionRouteChildren =
  {
    CommunicationImpressionProductRoute: CommunicationImpressionProductRoute,
    CommunicationImpressionIndexRoute: CommunicationImpressionIndexRoute,
  }

const CommunicationImpressionRouteWithChildren =
  CommunicationImpressionRoute._addFileChildren(
    CommunicationImpressionRouteChildren,
  )

interface CommunicationSignaletiqueRouteChildren {
  CommunicationSignaletiqueProductRoute: typeof CommunicationSignaletiqueProductRoute
  CommunicationSignaletiqueIndexRoute: typeof CommunicationSignaletiqueIndexRoute
}

const CommunicationSignaletiqueRouteChildren: CommunicationSignaletiqueRouteChildren =
  {
    CommunicationSignaletiqueProductRoute:
      CommunicationSignaletiqueProductRoute,
    CommunicationSignaletiqueIndexRoute: CommunicationSignaletiqueIndexRoute,
  }

const CommunicationSignaletiqueRouteWithChildren =
  CommunicationSignaletiqueRoute._addFileChildren(
    CommunicationSignaletiqueRouteChildren,
  )

interface CommunicationRouteChildren {
  CommunicationCategoryRoute: typeof CommunicationCategoryRoute
  CommunicationImpressionRoute: typeof CommunicationImpressionRouteWithChildren
  CommunicationSignaletiqueRoute: typeof CommunicationSignaletiqueRouteWithChildren
  CommunicationIndexRoute: typeof CommunicationIndexRoute
}

const CommunicationRouteChildren: CommunicationRouteChildren = {
  CommunicationCategoryRoute: CommunicationCategoryRoute,
  CommunicationImpressionRoute: CommunicationImpressionRouteWithChildren,
  CommunicationSignaletiqueRoute: CommunicationSignaletiqueRouteWithChildren,
  CommunicationIndexRoute: CommunicationIndexRoute,
}

const CommunicationRouteWithChildren = CommunicationRoute._addFileChildren(
  CommunicationRouteChildren,
)

interface StandsRouteChildren {
  StandsProductRoute: typeof StandsProductRoute
  StandsIndexRoute: typeof StandsIndexRoute
}

const StandsRouteChildren: StandsRouteChildren = {
  StandsProductRoute: StandsProductRoute,
  StandsIndexRoute: StandsIndexRoute,
}

const StandsRouteWithChildren =
  StandsRoute._addFileChildren(StandsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunicationRoute: CommunicationRouteWithChildren,
  ContactRoute: ContactRoute,
  CreationsRoute: CreationsRoute,
  EvenementielRoute: EvenementielRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StandsRoute: StandsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
