/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandsRouteImport } from './routes/stands'
import { Route as PubliciteRouteImport } from './routes/publicite'
import { Route as EvenementielRouteImport } from './routes/evenementiel'
import { Route as CreationsRouteImport } from './routes/creations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StandsIndexRouteImport } from './routes/stands.index'
import { Route as StandsProductRouteImport } from './routes/stands.$product'

const StandsRoute = StandsRouteImport.update({
  id: '/stands',
  path: '/stands',
  getParentRoute: () => rootRouteImport,
} as any)
const PubliciteRoute = PubliciteRouteImport.update({
  id: '/publicite',
  path: '/publicite',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementielRoute = EvenementielRouteImport.update({
  id: '/evenementiel',
  path: '/evenementiel',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsRoute = CreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandsIndexRoute = StandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StandsRoute,
} as any)
const StandsProductRoute = StandsProductRouteImport.update({
  id: '/$product',
  path: '/$product',
  getParentRoute: () => StandsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRoute
  '/evenementiel': typeof EvenementielRoute
  '/publicite': typeof PubliciteRoute
  '/stands': typeof StandsRouteWithChildren
  '/stands/$product': typeof StandsProductRoute
  '/stands/': typeof StandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRoute
  '/evenementiel': typeof EvenementielRoute
  '/publicite': typeof PubliciteRoute
  '/stands/$product': typeof StandsProductRoute
  '/stands': typeof StandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRoute
  '/evenementiel': typeof EvenementielRoute
  '/publicite': typeof PubliciteRoute
  '/stands': typeof StandsRouteWithChildren
  '/stands/$product': typeof StandsProductRoute
  '/stands/': typeof StandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/creations'
    | '/evenementiel'
    | '/publicite'
    | '/stands'
    | '/stands/$product'
    | '/stands/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/creations'
    | '/evenementiel'
    | '/publicite'
    | '/stands/$product'
    | '/stands'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/creations'
    | '/evenementiel'
    | '/publicite'
    | '/stands'
    | '/stands/$product'
    | '/stands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CreationsRoute: typeof CreationsRoute
  EvenementielRoute: typeof EvenementielRoute
  PubliciteRoute: typeof PubliciteRoute
  StandsRoute: typeof StandsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stands': {
      id: '/stands'
      path: '/stands'
      fullPath: '/stands'
      preLoaderRoute: typeof StandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicite': {
      id: '/publicite'
      path: '/publicite'
      fullPath: '/publicite'
      preLoaderRoute: typeof PubliciteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenementiel': {
      id: '/evenementiel'
      path: '/evenementiel'
      fullPath: '/evenementiel'
      preLoaderRoute: typeof EvenementielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations': {
      id: '/creations'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof CreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stands/': {
      id: '/stands/'
      path: '/'
      fullPath: '/stands/'
      preLoaderRoute: typeof StandsIndexRouteImport
      parentRoute: typeof StandsRoute
    }
    '/stands/$product': {
      id: '/stands/$product'
      path: '/$product'
      fullPath: '/stands/$product'
      preLoaderRoute: typeof StandsProductRouteImport
      parentRoute: typeof StandsRoute
    }
  }
}

interface StandsRouteChildren {
  StandsProductRoute: typeof StandsProductRoute
  StandsIndexRoute: typeof StandsIndexRoute
}

const StandsRouteChildren: StandsRouteChildren = {
  StandsProductRoute: StandsProductRoute,
  StandsIndexRoute: StandsIndexRoute,
}

const StandsRouteWithChildren =
  StandsRoute._addFileChildren(StandsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CreationsRoute: CreationsRoute,
  EvenementielRoute: EvenementielRoute,
  PubliciteRoute: PubliciteRoute,
  StandsRoute: StandsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
